name: Check app updates

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for updates
        run: |
          ./update.py
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          git clone https://github.com/runcitadel/dev-tools
          cd dev-tools
          yarn && yarn tsc
          yarn citadel-dev appcheck -d ../apps
          cd ..
          rm -rf dev-tools
          ./update.py
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -a -m "Update apps"  || true
          git push
